print()
print("Hello world\nHello world")
print()
print("Hello" + "Amaira")
print()
print("Hello " + "Amaira")
print('Hello' + " Amaira")
print("Hello" + ' ' + "Amaira")
print()
print("Hello, good morning\nHave an amazing day!")
# print("Hello, good morning/nHave an amazing day!")
print()
